#!/bin/bash

IP=`ifconfig  | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -n1`
DISK="/home"
RTORRENT="n"
RAPIDLEECH="n"
VNC="n"
DELUGE="n"
MOUNTPOINT="/home"

if [ -f "/etc/gentoo-release" ] ; then
  OS=gentoo
elif [ -f "/etc/debian_version" ] ; then
  OS=debian
fi

create_user() {
  mkdir $DISK/$NICK
  useradd -d $DISK/$NICK $NICK
}

set_rtorrent() {
  XMLRPC=/RPC`cat /dev/urandom | tr -dc 0-9 | head -c10`
  PORT=2`cat /dev/urandom | tr -dc 0-9 | head -c4`
  mkdir /var/rutorrent/rutorrent/conf/users/$NICK
  echo "<?php
  \$scgi_port = 0;
  \$scgi_host = \"unix://$DISK/$NICK/rtorrent/rpc.socket\";
  \$XMLRPCMountPoint = \"$XMLRPC\";
  ?>" > /var/rutorrent/rutorrent/conf/users/$NICK/config.php
  mkdir $DISK/$NICK/{downloads,rtorrent}
  echo "execute = {sh,-c,rm -f $DISK/$NICK/rtorrent/rpc.socket}
  scgi_local = $DISK/$NICK/rtorrent/rpc.socket
  execute = {sh,-c,chmod 0666 $DISK/$NICK/rtorrent/rpc.socket}
  encoding_list = UTF-8
  port_range = $PORT-$PORT
  port_random = no
  check_hash = no
  directory = $DISK/$NICK/downloads
  session = $DISK/$NICK/rtorrent
  dht = disable
  peer_exchange = no
  execute = {sh,-c,/usr/bin/php /var/rutorrent/rutorrent/php/initplugins.php $NICK &}" > $DISK/$NICK/.rtorrent.rc
  echo "scheduler.max_active.set = $PROCESS" >> $DISK/$NICK/.rtorrent.rc
  ./htpasswd.py -b -c 1 $NICK $PASSWORDVALUE
  if [ $OS = "debian" ] ; then
          cat 1 >> /usr/local/lighttpd/rutorrent_passwd
  elif [ $OS = "gentoo" ] ; then
          cat 1 >> /etc/lighttpd/rutorrent_passwd
  fi
 
}

set_rapidleech() {
  mkdir $DISK/$NICK/public_html
  svn checkout http://rapidleech.googlecode.com/svn/trunk/ rapidleech-read-only
  mv rapidleech-read-only $DISK/$NICK/public_html/rl
  if [ $OS = "debian" ] ; then
    cp /usr/bin/rar $DISK/$NICK/public_html/rl/rar/
  elif [ $OS = "gentoo" ] ; then
    cp /opt/rar/rar $DISK/$NICK/public_html/rl/rar/
  fi
}

set_VNC() {
  mkdir $DISK/$NICK/.vnc
  cp .xscreensaver $DISK/$NICK/
  cp xstartup $DISK/$NICK/.vnc
  echo $NICK >> vnclist
}

set_quota() {
  quotatool -u $NICK -bl $((QUOTAVALUE*1024))M $MOUNTPOINT
}

set_password() {
  passwd $NICK
}

show() {
  chown -R $NICK:$NICK $DISK/$NICK/
  if [ $RTORRENT = "y" ] ; then
    chown root:root $DISK/$NICK/.rtorrent.rc
    chmod 644 $NICK:$NICK $DISK/$NICK/.rtorrent.rc
    echo "webUI: http://$IP/rutorrent"
     ./startrt start $NICK > /dev/null
  fi
  if [ $RAPIDLEECH = "y" ] ; then
    chmod +x $DISK/$NICK/public_html/rl/rar/*
    chown -R $NICK:$NICK $DISK/$NICK/public_html
    chmod -R 777 $DISK/$NICK/public_html/rl
    echo "Rapidleech: http://$IP/~$NICK/rl"
  fi
  if [ $VNC = "y" ] ; then
    chmod +x $DISK/$NICK/.vnc/xstartup
    ./startvnc start $NICK
  fi
  echo "FTP: $IP"
  echo "panel: http://woox.pl"
}

while [ $# -gt 0 ] ; do
  arg="$1"
  shift
  if [ "$arg" = "-n" ] ; then
    NICK="$1"
    create_user
    shift
  elif [ "$arg" = "-p" ] ; then
    PASSWORD=y
    PASSWORDVALUE="$1"
    set_password
    shift
  elif [ "$arg" = "-r" ] ; then
    RTORRENT=y
    PROCESS="$1"
    set_rtorrent
    shift
  elif [ "$arg" = "-rl" ] ; then
    RAPIDLEECH=y
    set_rapidleech
  elif [ "$arg" = "-v" ] ; then
    VNC=y
    set_VNC
  elif [ "$arg" = "-q" ] ; then
    QUOTA=y
    QUOTAVALUE="$1"
    set_quota
    shift
  elif [ "$arg" = "-d" ] ; then
    DISK="$1"
    shift
  elif [ "$arg" = "-mp" ] ; then
    MOUNTPOINT="$1"
    shift
  elif [ "$arg" = "--deluge" ] ; then
    DELUGE=y
    
  else
    echo "./add -n NICK -p PASSWORD [OPTIONS]"
  fi
done

show
 
