#!/bin/bash

IP=`ifconfig  | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -n1`
DISK="/home"
MOUNTPOINT="/home"

if [ -f "/etc/gentoo-release" ] ; then
  OS=gentoo
elif [ -f "/etc/debian_version" ] ; then
  OS=debian
fi

create_user() {
  mkdir $DISK/$NICK
  useradd -d $DISK/$NICK $NICK
  chown -R $NICK:$NICK $DISK/$NICK/
}

set_rtorrent() {
  PORT=2`cat /dev/urandom | tr -dc 0-9 | head -c4`
  mkdir /var/rutorrent/rutorrent/conf/users/$NICK
  echo "<?php
  \$scgi_port = 0;
  \$scgi_host = \"unix://$DISK/$NICK/.rtorrent/rpc.socket\";
  \$XMLRPCMountPoint = \"/RPC`cat /dev/urandom | tr -dc 0-9 | head -c10`\";
  ?>" > /var/rutorrent/rutorrent/conf/users/$NICK/config.php
  mkdir $DISK/$NICK/{downloads,\.rtorrent}
  echo "execute = {sh,-c,rm -f $DISK/$NICK/.rtorrent/rpc.socket}
  scgi_local = $DISK/$NICK/.rtorrent/rpc.socket
  execute = {sh,-c,chmod 0666 $DISK/$NICK/.rtorrent/rpc.socket}
  encoding_list = UTF-8
  port_range = $PORT-$PORT
  port_random = no
  check_hash = no
  directory = $DISK/$NICK/downloads
  session = $DISK/$NICK/.rtorrent
  dht = disable
  peer_exchange = no
  execute = {sh,-c,/usr/bin/php /var/rutorrent/rutorrent/php/initplugins.php $NICK &}
  scheduler.max_active.set = $PROCESS" > $DISK/$NICK/.rtorrent.rc
  ./htpasswd.py -b -c 1 $NICK $PASSWORDVALUE
  if [ $OS = "debian" ] ; then
          cat 1 >> /usr/local/lighttpd/rutorrent_passwd
  elif [ $OS = "gentoo" ] ; then
          cat 1 >> /etc/lighttpd/rutorrent_passwd
  fi
  rm 1
  chown root:root $DISK/$NICK/.rtorrent.rc
  chmod 644 $DISK/$NICK/.rtorrent.rc
  chown -R $NICK:$NICK $DISK/$NICK/{downloads,\.rtorrent}
  ./startrt start $NICK > /dev/null
  mkdir -p /var/rutorrent/rutorrent/share/users/$NICK/{settings,torrents}
  chown -R lighttpd:$NICK /var/rutorrent/rutorrent/share/users/$NICK
  chmod -R 771 /var/rutorrent/rutorrent/share/users/$NICK
}

set_rapidleech() {
  mkdir $DISK/$NICK/public_html
  svn checkout http://rapidleech.googlecode.com/svn/trunk/ rapidleech-read-only
  mv rapidleech-read-only $DISK/$NICK/public_html/rl
  if [ $OS = "debian" ] ; then
    cp /usr/bin/rar $DISK/$NICK/public_html/rl/rar/
  elif [ $OS = "gentoo" ] ; then
    cp /opt/rar/rar $DISK/$NICK/public_html/rl/rar/
  fi
  chmod +x $DISK/$NICK/public_html/rl/rar/*
  chown -R $NICK:$NICK $DISK/$NICK/public_html
  chmod -R 777 $DISK/$NICK/public_html/rl
}

set_VNC() {
  mkdir $DISK/$NICK/.vnc
  cp .xscreensaver $DISK/$NICK/
  cp xstartup $DISK/$NICK/.vnc
  chown -R $NICK:$NICK $DISK/$NICK/.vnc
  chmod +x $DISK/$NICK/.vnc/xstartup
  echo $NICK >> vnclist
}

set_quota() {
  quotatool -u $NICK -bl $((QUOTAVALUE*1024))M $MOUNTPOINT
}

set_password() {
  passwd $NICK
}

set_transfer_limit() {
  # zaokraglanie limitu
  VALUE=`echo $(($TRANSFERLIMITVALUE*1024*1024*1024*1024)) | awk -F'.' '{print $1}'`
  iptables -A OUTPUT -p tcp -m owner --uid-owner $NICK -m quota --quota $VALUE -j ACCEPT
  iptables -A OUTPUT -p tcp -m owner --uid-owner $NICK -j DROP
  iptables-save > iptables
}

final() {
  if [ $RTORRENT ] ; then
    echo "webUI: http://$IP/rutorrent"
  fi
  if [ $RAPIDLEECH ] ; then
    echo "Rapidleech: http://$IP/~$NICK/rl"
  fi
  if [ $VNC ] ; then
    ./startvnc start $NICK
  fi
  echo "FTP: $IP"
  echo "panel: http://woox.pl"
}

while [ $# -gt 0 ] ; do
  arg="$1"
  shift
  if [ "$arg" = "-n" ] ; then
    NICK="$1"
    create_user
    shift
  elif [ "$arg" = "-p" ] ; then
    PASSWORDVALUE="$1"
    set_password
    shift
  elif [ "$arg" = "-r" ] ; then
    RTORRENT=y
    PROCESS="$1"
    set_rtorrent
    shift
  elif [ "$arg" = "-rl" ] ; then
    RAPIDLEECH=y
    set_rapidleech
  elif [ "$arg" = "-v" ] ; then
    VNC=y
    set_VNC
  elif [ "$arg" = "-q" ] ; then
    QUOTAVALUE="$1"
    set_quota
    shift
  elif [ "$arg" = "-d" ] ; then
    DISK="$1"
    shift
  elif [ "$arg" = "-mp" ] ; then
    MOUNTPOINT="$1"
    shift
  elif [ "$arg" = "--deluge" ] ; then
    DELUGE=y
  elif [ "$arg" = "-t" ] ; then
    TRANSFERLIMITVALUE="$1"
    set_transfer_limit
    shift
  else
    echo "./add -n NICK -p PASSWORD [OPTIONS]"
  fi
done

final