#!/bin/bash

USER=$1
HAVEVNC=`cat vnclist | grep -x $USER | wc -l`
HAVERT=`ls /var/rutorrent/rutorrent/conf/users | grep -w $USER | wc -l`

createArchive() {
	mkdir /root/archiwum/$USER
	updatedb
	locate $USER > /root/archiwum/$USER/$USER.torrents
	if [ -f "/etc/gentoo-release" ] ; then
		cat /var/log/lighttpd/access.log | grep $USER | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u > /root/archiwum/$USER/$USER.ip
		zcat /var/log/lighttpd/*gz | grep $USER | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u >> /root/archiwum/$USER/$USER.ip
	elif [ -f "/etc/debian_version" ] ; then
		cat /usr/local/lighttpd/logs/access.log | grep $USER | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u >> /root/archiwum/$USER/$USER.ip
		cat /usr/local/lighttpd/logs/access.log.1 | grep $USER | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u >> /root/archiwum/$USER/$USER.ip
		zcat /usr/local/lighttpd/logs/*gz | grep $USER | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort -u >> /root/archiwum/$USER/$USER.ip
	fi
	cat /root/archiwum/$USER/$USER.ip | sort -u > /root/archiwum/$USER.ip-new
	mv /root/archiwum/$USER.ip-new /root/archiwum/$USER/$USER.ip
}




if [ -d /root/archiwum ] ; then
	createArchive
else
	mkdir /root/archiwum
	createArchive
fi

pkill -SIGKILL -u $USER
userdel -rf $USER
rm -rf /var/rutorrent/rutorrent/conf/users/$USER
rm -rf /var/run/screen/$USER

if [ $HAVEVNC != '0' ] ; then
	sed /$USER/d vnclist > tmp
	cat tmp > vnclits
    rm tmp
fi

rm -rf /home/$USER
if [ -d /home2 ] ; then
	rm -rf /home2/$USER
fi
