#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

scan() {
  for file in $1 ; do
    if [ `transmission-show $file | grep Public | wc -l` != 0 ] ; then
      echo $file
      rm $file
    fi
  done
}

scan "/home/*/.config/transmission-daemon/torrents/*"
scan "/home/*/.rtorrent/*.torrent"
