#!/bin/bash

load=`cat /proc/loadavg | tr " " "_"`
hostname=`hostname`
# Zmienna przechowująca dane do wyslania skryptowi PHP
array=""

# Zmienne do obliczania wykorzystania lacza serwera
interface=$1
received_bytes=""
old_received_bytes=""
transmitted_bytes=""
old_transmitted_bytes=""

action=`sh /root/startrt status all`

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for rtUsers in $action ; do
	if [ ${rtUsers:1:1} = "1" ]
		then ttt="${rtUsers:4}=1"
	elif [ ${rtUsers:1:1} = "0" ]
		then ttt="${rtUsers:4}=0"
	else
		ttt="${rtUsers:4}=0"
	fi
	array=''$array'&'$ttt''
done

IFS=$SAVEIFS

hdd_file=`du -h --max-depth=1 /home | awk -F/home/ '{print $2 ";" $1}' | grep -v /home| grep -v ftp | grep -v lost+found | tr "\t\t\n \v" "_____"`
if [ -d /home2 ]; then
  hdd_file2=`du -h --max-depth=1 /home2 | awk -F/home2/ '{print $2 ";" $1}' | grep -v /home2 | grep -v ftp | grep -v lost+found | tr "\t\t\n \v" "_____"`
fi

hdd=`echo "${hdd_file}$hdd_file2"`

transfer1=`iptables -L OUTPUT -v | grep ACCEPT | awk '{print $13 "_" $2}' | tail -n +2 | tr "\n" ";"`
transfer2=`iptables -t mangle -L POSTROUTING -v | grep ACCEPT | awk '{print $13 "_" $2}' | tail -n +2 | tr "\n" ";"`
transfer=`echo ${transfer1}${transfer2}`

# This function parses /proc/net/dev file searching for a line containing $interface data.
# Within that line, the first and ninth numbers after ':' are respectively the received and transmited bytes.
get_bytes() {
    line=$(cat /proc/net/dev | grep eth0 | cut -d ':' -f 2 | awk '{print "received_bytes="$1, "transmitted_bytes="$9}')
    eval $line
}
 
# Function which calculates the speed using actual and old byte number.
# Speed is shown in KByte per second when greater or equal than 1 KByte per second.
# This function should be called each second.
get_velocity() {
    value=$1
    old_value=$2
 
    let vel=$value-$old_value
    let velKB=$vel/1024/5

 echo -n "$velKB";

}


# Gets initial values.
get_bytes
old_received_bytes=$received_bytes
old_transmitted_bytes=$transmitted_bytes
 
# Shows a message and waits for one second.
sleep 5;

 

# Get new transmitted and received byte number values.
get_bytes
 
# Calculates speeds.
vel_recv=$(get_velocity $received_bytes $old_received_bytes)
vel_trans=$(get_velocity $transmitted_bytes $old_transmitted_bytes)


/usr/bin/wget -q -O - 'http://woox.pl/woox.php?info2=1&upload='$vel_trans'&download='$vel_recv'&host='$hostname'' >/dev/null 2>&1
/usr/bin/wget -q -O - 'http://woox.pl/woox.php?info=1&load='$load'&dysk='$hdd'&host='$hostname'' >/dev/null 2>&1
/usr/bin/wget -q -O - 'http://woox.pl/woox.php?uzytkownicy=1'$array'' >/dev/null 2>&1 
/usr/bin/wget -q -O - 'http://woox.pl/woox.php?info3=1&transfer='$transfer'' >/dev/null 2>&1 
