#!/bin/bash

USER=$1
PASSWORD=$2

HAVEVNC=`cat vnclist | grep -x $USER | wc -l`
HAVERT=`ls /var/rutorrent/rutorrent/conf/users | grep -w $USER | wc -l`

if [ -f "/etc/gentoo-release" ] ; then
	RUTORRENT_PASSWD='/etc/lighttpd/rutorrent_passwd'
elif [ -f "/etc/debian_version" ] ; then
        RUTORRENT_PASSWD='/usr/local/lighttpd/rutorrent_passwd'
fi

passwd $USER
if [ $HAVERT != '0' ] ; then
	sed /$USER/d $RUTORRENT_PASSWD > tmp
	cat tmp > $RUTORRENT_PASSWD
	./htpasswd.py -b -c 1 $USER $PASSWORD
	cat 1 >> $RUTORRENT_PASSWD
fi
if [ $HAVEVNC != '0' ] ; then
	su $USER -c "vncpasswd"
fi
