#!/bin/bash

ACTION=$1
USER=$2

checkUser() {
	ISSTARTED=`ps aux | grep $USER | grep deluge | wc -l`
	HAVEVNC=`cat vnclist | grep -w $USER | wc -l`
	IP=`ifconfig  | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -n1`
	if [ ! -e vnclist ] ; then
		touch delugelist
	fi
	if [ $HAVEDELUGE = '0' ] ; then
		echo "$USER - nie posiada deluge" 
		exit
	fi
}