#!/bin/bash

ACTION=$1
USER=$2
PATH_SCRIPT="$(readlink -f ${BASH_SOURCE[0]})"

check_user() {
    VNCPORT=`ps aux | grep $1 | \ egrep -o "Xvnc[4]{0,1} \:[0-9]{1,2}" | \
        awk '{print $2}'`
    ISSTARTED=`pgrep -u $1 vnc | wc -l`
    HAVEVNC=`cat vnclist | grep -x $1 | wc -l`
    IP=`ifconfig  | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" | head -n1`
    DISKQUOTA=`repquota -u -s -a | grep $1 | awk '{print $2'} | \
        tail -n1`
    if [ ! -e vnclist ] ; then
        touch vnclist
    fi
    if [ $HAVEVNC = '0' ] ; then
        echo "$1 - nie posiada vnc"
        exit
    fi
}

start_VNC() {
    if [ $ISSTARTED != '0' ] ; then
        echo "$1 - vnc jest już uruchomione"
    elif [ $DISKQUOTA = '+-' ] ; then
        echo "$1 - przekroczone miejsce na dysku"
    else
        su $1 -c "vncserver 2> /dev/null"
        check_user
        echo "$1 - vnc zostało prawidłowo uruchomione"
        echo "VNC: $IP$VNCPORT"
    fi
}

stop_VNC() {
    if [ $ISSTARTED = '0' ] ; then
        echo "$1 - vnc jest już zatrzymane"
    else
    su $1 -c "vncserver -kill $VNCPORT 2> /dev/null"
        echo "$1 - vnc zostało zatrzymane"
    fi
}

restart_VNC() {
    stop_VNC
    sleep 2s
    start_VNC
}

status_VNC() {
    if [ $ISSTARTED = '0' ] ; then
        echo "(0) $1"
    elif [ $ISSTARTED > '0' ] ; then
        echo "(1) $1 - $IP$VNCPORT"
    fi
}

action_all() {
    for vnc_users in `cat vnclist` ; do
        $PATH_SCRIPT $1 $vnc_users
    done
}

if [ $USER = "all" ] ; then
    if [ $ACTION = "start" ] ; then
        action_all start
    elif [ $ACTION = "stop" ] ; then
        action_all stop
    elif [ $ACTION = "restart" ] ; then
        action_all restart
    elif [ $ACTION = "status" ] ; then
        action_all status
    fi

elif [ $USER != "all" ] ; then
    check_user $USER
    if [ $ACTION = 'start' ] ; then
        start_VNC $USER
    elif [ $ACTION = 'stop' ] ; then
        stop_VNC $USER
    elif [ $ACTION = 'restart' ] ; then
        restart_VNC $USER
    elif [ $ACTION = 'status' ] ; then
        status_VNC $USER
    fi
fi
