#!/bin/bash

ACTION=$1
USER=$2

check_user() {
    if [ ! -e exclude ] ; then
        touch exclude
    fi
    EXIST=`ls /var/rutorrent/rutorrent/conf/users | grep -w $USER | \
        wc -l`
    if [ $EXIST = '0' ] ; then
        echo "$USER - nie posiada rtorrenta"
        exit
    fi
    ISSTARTED=`pgrep -u $USER rtorrent | wc -l`
    if [ -a /usr/sbin/repquota ] ; then
        DISKQUOTA=`repquota -u -s -a | grep $USER | awk '{print $2'} | \
            tail -n1`
    else
        DISKQUOTA=0
    fi
}

start_process() {
    su $USER -c "screen -dmS rtorrent rtorrent"
    echo "$USER - czekam 5 sekund na potwierdzenie działania rtorrenta"
    sleep 5s
}

start_rt() {
    for ((c=0; c<4; c++)) ; do
        check_user
        if [ $ISSTARTED != '0' ] ; then
            echo "$USER - rtorrent jest już uruchomiony"
            break
        # TODO: Find a better way for checking quota
        elif [ $c = '0' ] && [ $DISKQUOTA = '+-' ] ; then
            echo "$USER - przekroczone miejsce na dysku"
            break
	elif [ $c = '0' ] ; then
            start_process
        elif [ $c = '1' ] ; then
            echo "$USER - kasuje pliki rtorrenta i sesji screen"
            rm -f /home*/$USER/.rtorrent/rpc.socket
            rm -f /home*/$USER/.rtorrent/rtorrent.lock
            # Legacy
            rm -f /home*/$USER/rtorrent/rpc.socket
            rm -f /home*/$USER/rtorrent/rtorrent.lock
            rm -f /home*/$USER/rtorrent/session/rpc.socket
            rm -f /home*/$USER/rtorrent/session/rtorrent.lock
            rm -fr /var/run/screen/S-$USER
            start_process
        elif [ $c = '2' ] ; then
            echo "$USER - Usuwam wszystkie załadowane torrenty"
            rm -f /home*/$USER/.rtorrent/*
            # Legacy
            rm -f /home*/$USER/rtorrent/session/*
            rm -f /home*/$USER/rtorrent/*
            start_process
        fi
    done
}

stop_rt() {
    check_user
    if [ $ISSTARTED = '0' ] ; then
        echo "$USER - rtorrent jest już zatrzymany"
    else
        pkill -SIGTERM -u $USER rtorrent
        echo "$USER - rtorrent został zatrzymany"
    fi
}

restart_rt() {
    stop_rt
    sleep 2s
    start_rt
}

status_rt() {
    check_user
    if [ $ISSTARTED = '0' ] ; then
        echo "(0) $USER"
    else
        echo "(1) $USER"
    fi
}

action_all() {
    for rt_users in /var/rutorrent/rutorrent/conf/users/* ; do
        rt_users=`echo $rt_users | \
            sed -e 's/\/var\/rutorrent\/rutorrent\/conf\/users\///g'`
        if [ `cat exclude | grep $rt_users | wc -l` != 1 ] ; then
            /root/startrt $1 $rt_users
        else
            echo "$rt_users ma wyłączone konto"
        fi
    done
}

if [ $USER = "all" ] ; then
    if [ $ACTION = "start" ] ; then
        action_all start
    elif [ $ACTION = "stop" ] ; then
        action_all stop
    elif [ $ACTION = "restart" ] ; then
        action_all restart
    elif [ $ACTION = "status" ] ; then
        action_all status
    fi

elif [ $USER != "all" ] ; then
    if [ $ACTION = "start" ] ; then
        start_rt
    elif [ $ACTION = "stop" ] ; then
        stop_rt
    elif [ $ACTION = "restart" ] ; then
        restart_rt
    elif [ $ACTION = "status" ] ; then
        status_rt
    fi
fi
