#!/bin/bash

USERID=`cat /etc/passwd | grep $1 | awk -F: '{print $3}'`
cat /etc/iptables | grep -v $USERID > /tmp/iptables
iptables-restore < /tmp/iptables
rm /tmp/iptables
echo "$USER - został odblokowany"
