#!/bin/bash

ACTION=$1
PARAM=$2

if [ $ACTION = "block" ] ; then
    iptables -A OUTPUT -p tcp -m owner --uid-owner $2 -j DROP
    echo "User $2 został zablokowany"
elif [ $ACTION = "unblock" ] ; then
    line_number=`iptables -L OUTPUT --line-numbers | grep $2 | awk '{print $1}'`
    iptables -D OUTPUT $line_number
    echo "User $2 został odblokowany"
elif [ $ACTION = "transfer-restart" ] ; then
    line_number=`iptables -t mangle -L POSTROUTING -v --line-numbers | grep ACCEPT | grep $2 | awk '{print $1}'`
    iptables -t mangle -D POSTROUTING $line_number
    iptables -t mangle -I POSTROUTING $line_number -o eth0 -p tcp -m owner --uid-owner $2 -m quota --quota $(($3*1024*1024*1024)) -j ACCEPT
elif [ $ACTION = "passwd" ] ; then
    HAVEVNC=`cat vnclist | grep -x $PARAM | wc -l`
    HAVERT=`ls /var/rutorrent/rutorrent/conf/users | grep -w $PARAM | wc -l`
    RUTORRENT_PASSWD='/usr/local/lighttpd/rutorrent_passwd'
    passwd $PARAM
    if [ $HAVERT != '0' ] ; then
        sed /$PARAM/d $RUTORRENT_PASSWD > tmp
	cat tmp > $RUTORRENT_PASSWD
	./htpasswd.py -b -c 1 $PARAM $3
	cat 1 >> $RUTORRENT_PASSWD
	rm tmp
    fi
    if [ $HAVEVNC != '0' ] ; then
	su $USER -c "vncpasswd"
    fi
fi
